"""добавлены builds

Revision ID: d59c6bc24bcb
Revises: c8d5cbea5421
Create Date: 2025-04-19 19:04:25.669254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59c6bc24bcb'
down_revision: Union[str, None] = 'c8d5cbea5421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
